### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by A-hamza44** [GM223/PKrs_currency#1]

**Comment by A-hamza44** [comment]
Hi sir
I have issue in this code.
The Error is" 0curl: (6) Could not resolve host: course-v3.fast.ai"
Please Solved.
Thank You.

**Comment by GM223** [comment]
Hi Hamza,

I will not be updating the code to the latest fast.ai API.
Sorry about that.

**Comment by A-hamza44** [comment]
Thanks for Replying.
Please help me in currency recognition.Because my FYP is almost done just
issue in currency recognition.
